import test from"node:test";import assert from"node:assert/strict";import{accrueTime,createSession,exactMatch,scoreSession,shuffledUnique}from"../lib/engine.ts";import{elapsedSeconds,isExpired,remainingSeconds}from"../lib/time.ts";import{fullExamEligibleQuestions,isFullExamEligible,validateQuestionBank}from"../lib/question-validation.ts";import{aggregateMistakes,performance}from"../lib/analytics.ts";import{upsertAttempt}from"../lib/storage.ts";import{questions}from"../data/questions.ts";import{lifeSafetyQuestions}from"../data/questions-life-safety.ts";import{energyQuestions}from"../data/questions-energy.ts";import{foundationQuestions}from"../data/questions-foundations.ts";import{carpentryQuestions}from"../data/questions-carpentry.ts";import type{Attempt,Question,Session}from"../lib/types.ts";
const clone=<T>(x:T):T=>structuredClone(x),base=()=>clone(questions[0]);
const reviewed=()=>{const q=base();q.editorialStatus="reviewed";q.verificationStatus="source-checked";q.reference={source:"Official test source",section:"Test section"};q.answers.push({id:"e",text:"Fifth plausible answer"});return q};
const session=(ids:string[],selected:Record<string,string[]>={},start=0):Session=>({id:"s",questionBankVersion:1,mode:"quick-test",startedAt:start,questionIds:ids,currentIndex:0,selectedAnswers:selected,flaggedQuestionIds:[],questionTimeSeconds:{},activeQuestionEnteredAt:start,checkedQuestionIds:[]});
const attempt=(id:string,qids:string[],correctness:Record<string,boolean>,selected:Record<string,string[]>={}):Attempt=>({id,questionBankVersion:1,mode:"quick-test",startedAt:0,completedAt:1000,durationSeconds:1,questionIds:qids,selectedAnswers:selected,correctness,questionTimeSeconds:{},flaggedQuestionIds:[],correct:Object.values(correctness).filter(Boolean).length,incorrect:0,unanswered:0,percentage:0,passed:false});

test("canonical bank validates",()=>assert.deepEqual(validateQuestionBank(questions),[]));
for(const [name,mutate,field]of[
 ["duplicate question IDs",(b:Question[])=>b.push(clone(b[0])),"id"],
 ["unknown correct answer",(b:Question[])=>b[0].correctAnswers=["missing"],"correctAnswers"],
 ["single with two correct answers",(b:Question[])=>b[0].correctAnswers=["a","b"],"correctAnswers"],
 ["multiple with one correct answer",(b:Question[])=>{b[0].type="multiple";b[0].correctAnswers=["a"]},"correctAnswers"],
 ["mismatched required selections",(b:Question[])=>b[0].requiredSelections=2,"requiredSelections"],
 ["duplicate answer IDs",(b:Question[])=>b[0].answers[1].id=b[0].answers[0].id,"answers.id"],
]as const)test(`validation rejects ${name}`,()=>{const b=[base()];mutate(b);assert.ok(validateQuestionBank(b).some(x=>x.field===field))});

test("selection is deterministic, unique, bounded, and non-mutating",()=>{const items=[{id:"1",answers:[1]},{id:"2",answers:[2]},{id:"3",answers:[3]}],before=clone(items),a=shuffledUnique(items,2,()=>0);assert.deepEqual(a.map(x=>x.id),["2","3"]);assert.equal(new Set(a.map(x=>x.id)).size,2);assert.equal(shuffledUnique(items,99,()=>.5).length,3);assert.deepEqual(items,before)});
test("quick/category generation clamps count and preserves bank",()=>{const bank=questions.slice(0,3),before=clone(bank),s=createSession("quick-test",bank,20,0,()=>"id");assert.equal(s.questionIds.length,3);assert.equal(new Set(s.questionIds).size,3);assert.deepEqual(bank,before)});
test("full exam refuses an insufficient bank",()=>assert.throws(()=>createSession("full-exam",questions.filter(q=>q.id!=="carpentry-035"),110,0,()=>"id"),/requires at least 110/));
test("full exam creates exactly 110 unique questions",()=>{const seed=reviewed(),bank=Array.from({length:111},(_,i)=>({...clone(seed),id:`q${i}`}));const s=createSession("full-exam",bank,999,0,()=>"id");assert.equal(s.questionIds.length,110);assert.equal(new Set(s.questionIds).size,110)});
test("generation rejects duplicate eligible IDs",()=>assert.throws(()=>createSession("quick-test",[base(),base()],2,0,()=>"id"),/unique/));

for(const [selected,expected,label]of[[["a","c","e"],true,"exact"],[["e","a","c"],true,"order independent"],[["a","c"],false,"missing"],[["a","c","e","b"],false,"extra"],[["a","c","d"],false,"wrong same size"],[[],false,"empty"],[["a","c","e","e"],false,"duplicate selected"]]as const)test(`multiple scoring: ${label}`,()=>assert.equal(exactMatch([...selected],["a","c","e"]),expected));
test("single choice correct and incorrect",()=>{assert.equal(exactMatch(["b"],["b"]),true);assert.equal(exactMatch(["a"],["b"]),false)});
test("unanswered is incorrect and separately counted",()=>{const q=base(),a=scoreSession(session([q.id]),[q],1000);assert.equal(a.correct,0);assert.equal(a.incorrect,0);assert.equal(a.unanswered,1);assert.equal(a.correctness[q.id],false)});
for(const [correct,total,passed]of[[7,10,true],[6,10,false],[8,10,true]]as const)test(`${correct}/${total} pass boundary is ${passed}`,()=>{const seed=base(),bank=Array.from({length:total},(_,i)=>({...clone(seed),id:`q${i}`})),selected=Object.fromEntries(bank.slice(0,correct).map(q=>[q.id,q.correctAnswers])),a=scoreSession(session(bank.map(q=>q.id),selected),bank,1000);assert.equal(a.passed,passed);assert.equal(a.percentage,correct/total*100)});

test("timestamp helpers floor elapsed and remaining at zero",()=>{assert.equal(elapsedSeconds(1000,3500),2);assert.equal(remainingSeconds(1000,10,3500),8);assert.equal(remainingSeconds(1000,1,99999),0);assert.equal(isExpired(1000,1,2000),true)});
test("question time accrues once without mutating session",()=>{const s=session(["q"],{},1000),a=accrueTime(s,4500),b=accrueTime(a,6500);assert.equal(s.questionTimeSeconds.q,undefined);assert.equal(a.questionTimeSeconds.q,3);assert.equal(b.questionTimeSeconds.q,5)});
test("session restore fields remain stable when active marker resets",()=>{const s={...session(["a","b"],{a:["x"]},10),currentIndex:1,flaggedQuestionIds:["a"],checkedQuestionIds:["a"],questionTimeSeconds:{a:4}},restored={...clone(s),activeQuestionEnteredAt:99};for(const key of["id","questionIds","currentIndex","selectedAnswers","flaggedQuestionIds","checkedQuestionIds","questionTimeSeconds","startedAt"]as const)assert.deepEqual(restored[key],s[key])});

test("performance deduplicates question IDs and repeated language tags",()=>{const q={...base(),languageTags:["NOT","NOT"]},a=attempt("a",[q.id,q.id],{[q.id]:true});assert.deepEqual(performance([a],[q],"languageTags"),[{name:"NOT",correct:1,total:1,percentage:100}]);assert.equal(performance([a],[q],"subcategory")[0].total,1)});
test("performance is empty without data",()=>assert.deepEqual(performance([],questions,"subcategory"),[]));
test("mistakes aggregate attempts, unanswered, latest result, and duplicate IDs once",()=>{const q=base(),rows=aggregateMistakes([attempt("new",[q.id],{[q.id]:true},{[q.id]:q.correctAnswers}),attempt("old",[q.id,q.id],{[q.id]:false})],[q]);assert.equal(rows[0].attempted,2);assert.equal(rows[0].missed,1);assert.equal(rows[0].unanswered,1);assert.equal(rows[0].latestCorrect,true)});
test("mistakes sort by misses then attempts",()=>{const a=base(),b={...base(),id:"b"},rows=aggregateMistakes([attempt("1",[a.id,b.id],{[a.id]:false,b:false}),attempt("2",[b.id],{b:false})],[a,b]);assert.equal(rows[0].question.id,"b")});
test("attempt completion upsert is idempotent",()=>{const a=attempt("same",[],{}),newer={...a,completedAt:2};assert.deepEqual(upsertAttempt(upsertAttempt([],a),newer),[newer])});


test("sample question is not Full Exam eligible",()=>assert.equal(isFullExamEligible(base()),false));
test("draft question is not Full Exam eligible",()=>{const q=reviewed();q.editorialStatus="draft";assert.equal(isFullExamEligible(q),false)});
test("reviewed but unverified question is not eligible",()=>{const q=reviewed();q.verificationStatus="unverified";assert.equal(isFullExamEligible(q),false)});
test("reviewed source-checked valid five-answer question is eligible",()=>assert.equal(isFullExamEligible(reviewed()),true));
test("reviewed four-answer question is not Full Exam eligible",()=>{const q=reviewed();q.answers.pop();assert.equal(isFullExamEligible(q),false)});
test("missing explanation fails eligibility",()=>{const q=reviewed();q.explanation="";assert.equal(isFullExamEligible(q),false)});
test("missing reference fails eligibility",()=>{const q=reviewed();q.reference=undefined;assert.equal(isFullExamEligible(q),false)});
test("Full Exam availability counts only eligible questions",()=>{const seed=reviewed(),eligible=Array.from({length:100},(_,i)=>({...clone(seed),id:`eligible-${i}`})),samples=Array.from({length:10},(_,i)=>({...base(),id:`sample-extra-${i}`}));assert.equal(fullExamEligibleQuestions([...eligible,...samples]).length,100);assert.throws(()=>createSession("full-exam",[...eligible,...samples],110,0,()=>"id"),/Current bank: 100/)});
test("110 eligible unique questions make Full Exam available",()=>{const seed=reviewed(),bank=Array.from({length:110},(_,i)=>({...clone(seed),id:`eligible-${i}`}));assert.equal(createSession("full-exam",bank,110,0,()=>"id").questionIds.length,110)});
test("Full Exam generator selects only eligible questions",()=>{const seed=reviewed(),bank=Array.from({length:110},(_,i)=>({...clone(seed),id:`eligible-${i}`}));bank.push({...base(),id:"sample-never-selected"});const session=createSession("full-exam",bank,110,0,()=>"id");assert.equal(session.questionIds.includes("sample-never-selected"),false)});


test("canonical serious reviewed questions have five answers",()=>assert.ok(questions.filter(q=>q.editorialStatus==="reviewed").every(q=>q.answers.length===5)));
test("canonical source-checked questions have precise sections and explanations",()=>assert.ok(questions.filter(q=>q.verificationStatus==="source-checked").every(q=>Boolean(q.reference?.source.trim()&&q.reference.section?.trim()&&q.explanation.trim()))));
test("canonical Full Exam eligibility equals the derived reviewed verified valid set",()=>{const expected=questions.filter(q=>q.editorialStatus==="reviewed"&&q.verificationStatus==="source-checked"&&q.answers.length===5&&validateQuestionBank([q]).length===0).map(q=>q.id);assert.deepEqual(fullExamEligibleQuestions(questions).map(q=>q.id),expected)});
test("canonical drafts and unverified records are excluded from Full Exam",()=>assert.ok(questions.filter(q=>q.editorialStatus==="draft"||q.verificationStatus==="unverified").every(q=>!isFullExamEligible(q))));
test("source-checked question without a precise section is structurally invalid and ineligible",()=>{const q=reviewed();q.reference={source:"Official test source"};assert.ok(validateQuestionBank([q]).some(x=>x.field==="reference.section"));assert.equal(isFullExamEligible(q),false)});

test("placeholder reference section cannot become source-checked eligibility",()=>{const q=reviewed();q.reference={source:"2020 Minnesota Residential Code",section:"Exact section not established — audit pending"};assert.ok(validateQuestionBank([q]).some(x=>x.field==="reference.section"));assert.equal(isFullExamEligible(q),false)});


test("Life Safety batch preserves exactly the original 25 stable IDs",()=>{assert.equal(lifeSafetyQuestions.length,25);assert.deepEqual(lifeSafetyQuestions.map(q=>q.id),Array.from({length:25},(_,i)=>`life-safety-draft-${String(i+1).padStart(3,"0")}`))});
test("Life Safety reviewed records are complete and precisely referenced",()=>{for(const q of lifeSafetyQuestions){assert.equal(q.editorialStatus,"reviewed");assert.equal(q.verificationStatus,"source-checked");assert.equal(q.answers.length,5);assert.ok(q.explanation.trim());assert.ok(q.reference?.section?.trim());assert.doesNotMatch(q.reference?.section??"",/pending|not established|tbd|todo/i)}});
test("Life Safety multiple-select counts are explicit and exact",()=>{const multiple=lifeSafetyQuestions.filter(q=>q.type==="multiple");assert.equal(multiple.length,6);for(const q of multiple){assert.match(q.question,/which (TWO|THREE)/i);assert.equal(q.requiredSelections,q.correctAnswers.length)}});
test("Life Safety reviewed distractors exclude junk filler patterns",()=>{const text=lifeSafetyQuestions.flatMap(q=>q.answers.map(a=>a.text)).join(" ");assert.doesNotMatch(text,/paint|landscap|invoice|vehicle|supplier|tool brand|roof color|brochure|warranty/i)});
test("canonical bank is 24 samples plus 110 verified questions",()=>{assert.equal(questions.length,134);assert.equal(questions.filter(q=>q.editorialStatus==="sample").length,24);assert.equal(questions.filter(q=>q.editorialStatus==="reviewed").length,110);assert.equal(questions.filter(q=>q.verificationStatus==="source-checked").length,110);assert.equal(fullExamEligibleQuestions(questions).length,110)});

test("Energy batch has exactly 25 unique stable IDs",()=>{assert.equal(energyQuestions.length,25);assert.deepEqual(energyQuestions.map(q=>q.id),Array.from({length:25},(_,i)=>`energy-${String(i+1).padStart(3,"0")}`));assert.equal(new Set(energyQuestions.map(q=>q.id)).size,25)});
test("Energy records are reviewed, source-checked, five-choice, and precisely referenced",()=>{for(const q of energyQuestions){assert.equal(q.primaryCategory,"Energy Code");assert.equal(q.editorialStatus,"reviewed");assert.equal(q.verificationStatus,"source-checked");assert.equal(q.answers.length,5);assert.ok(q.explanation.trim());assert.ok(q.reference?.source.trim());assert.ok(q.reference?.section?.trim());assert.doesNotMatch(q.reference?.section??"",/pending|not established|tbd|todo|placeholder/i)}});
test("Energy multiple-select counts are explicit and exact",()=>{const multiple=energyQuestions.filter(q=>q.type==="multiple");assert.equal(multiple.length,6);for(const q of multiple){assert.match(q.question,/which (TWO|THREE)/i);assert.equal(q.requiredSelections,q.correctAnswers.length)}});
test("Energy distractors exclude junk filler patterns",()=>{const text=energyQuestions.flatMap(q=>q.answers.map(a=>a.text)).join(" ");assert.doesNotMatch(text,/paint color|landscap|invoice|vehicle brand|tool brand|roof color|brochure|warranty length/i)});
test("legacy samples remain ineligible after Energy integration",()=>assert.ok(questions.filter(q=>q.editorialStatus==="sample").every(q=>!isFullExamEligible(q))));
test("Energy TVR and CVR answer keys match formula results",()=>{const tvr=energyQuestions.find(q=>q.id==="energy-015")!,cvr=energyQuestions.find(q=>q.id==="energy-021")!,floor=energyQuestions.find(q=>q.id==="energy-022")!;assert.equal(tvr.answers.find(a=>tvr.correctAnswers.includes(a.id))?.text,`${.02*2000+15*(3+1)} cfm`);assert.equal(cvr.answers.find(a=>cvr.correctAnswers.includes(a.id))?.text,`${(.02*2500+15*(4+1))/2} cfm`);assert.equal(floor.answers.find(a=>floor.correctAnswers.includes(a.id))?.text,"40 cfm")});


test("Foundations batch has exactly 25 unique stable IDs",()=>{assert.equal(foundationQuestions.length,25);assert.deepEqual(foundationQuestions.map(q=>q.id),Array.from({length:25},(_,i)=>`foundations-${String(i+1).padStart(3,"0")}`));assert.equal(new Set(foundationQuestions.map(q=>q.id)).size,25)});
test("Foundations records are reviewed, source-checked, five-choice, and precisely referenced",()=>{for(const q of foundationQuestions){assert.equal(q.primaryCategory,"Footings and Foundations");assert.equal(q.editorialStatus,"reviewed");assert.equal(q.verificationStatus,"source-checked");assert.equal(q.answers.length,5);assert.ok(q.explanation.trim());assert.equal(q.reference?.source,"2020 Minnesota Residential Code");assert.ok(q.reference.section?.trim());assert.doesNotMatch(q.reference.section,/pending|not established|tbd|todo|placeholder/i)}});
test("Foundations multiple-select counts are explicit and exact",()=>{const multiple=foundationQuestions.filter(q=>q.type==="multiple");assert.equal(multiple.length,6);for(const q of multiple){assert.match(q.question,/Which (TWO|THREE)/);assert.equal(q.requiredSelections,q.correctAnswers.length)}});
test("Foundations distractors exclude junk filler patterns",()=>{const text=foundationQuestions.flatMap(q=>q.answers.map(a=>a.text)).join(" ");assert.doesNotMatch(text,/paint color|supplier name|vehicle age|invoice length|brand name|tool brand|roof color|brochure/i)});
test("Foundations integration preserves 24 ineligible legacy samples",()=>{const samples=questions.filter(q=>q.editorialStatus==="sample");assert.equal(samples.length,24);assert.ok(samples.every(q=>!isFullExamEligible(q)))});
test("Foundations high-risk numeric answer keys remain fixed",()=>{const answer=(id:string)=>{const q=foundationQuestions.find(x=>x.id===id)!;return q.correctAnswers.map(key=>q.answers.find(a=>a.id===key)!.text)};assert.deepEqual(answer("foundations-002"),["5% to 7%"]);assert.deepEqual(answer("foundations-004"),["1/2 inch"]);assert.deepEqual(answer("foundations-010"),["7 inches"]);assert.deepEqual(answer("foundations-011"),["6 feet on center"]);assert.deepEqual(answer("foundations-012"),["Two bolts"]);assert.deepEqual(answer("foundations-013"),["3.5 inches thick"]);assert.deepEqual(answer("foundations-005"),["From the top of footing to finished grade"])});

test("Carpentry batch has exactly 35 unique sequential IDs",()=>{assert.equal(carpentryQuestions.length,35);assert.deepEqual(carpentryQuestions.map(q=>q.id),Array.from({length:35},(_,i)=>`carpentry-${String(i+1).padStart(3,"0")}`));assert.equal(new Set(questions.map(q=>q.id)).size,questions.length)});
test("Carpentry records are reviewed, source-checked, five-choice, and precisely referenced",()=>{for(const q of carpentryQuestions){assert.equal(q.primaryCategory,"Carpentry");assert.equal(q.answers.length,5);assert.equal(q.editorialStatus,"reviewed");assert.equal(q.verificationStatus,"source-checked");assert.ok(q.explanation.trim());assert.ok(q.reference?.source.trim());assert.ok(q.reference?.section?.trim());assert.ok(q.reference?.title?.trim());assert.doesNotMatch(`${q.reference?.source} ${q.reference?.section}`,/pending|not established|tbd|todo|placeholder/i)}});
test("Carpentry multiple-select counts are explicit and exact",()=>{const multiple=carpentryQuestions.filter(q=>q.type==="multiple");assert.equal(multiple.length,8);for(const q of multiple){assert.match(q.question,/Which (TWO|THREE)/);assert.equal(q.requiredSelections,q.correctAnswers.length)}});
test("Carpentry distractors exclude junk filler patterns",()=>{const text=carpentryQuestions.flatMap(q=>q.answers.map(a=>a.text)).join(" ");assert.doesNotMatch(text,/paint color|supplier name|vehicle age|invoice|brand name|appliance color|roof color|brochure/i)});
test("Carpentry difficulty and applied-skill distribution matches batch plan",()=>{assert.deepEqual(Object.fromEntries(["easy","medium","exam"].map(d=>[d,carpentryQuestions.filter(q=>q.difficulty===d).length])),{easy:7,medium:14,exam:14});assert.equal(carpentryQuestions.filter(q=>q.skills.some(s=>["table reading","construction math","measurement"].includes(s))).length,8)});
test("canonical Full Exam is ready and selects exactly 110 unique eligible questions",()=>{const eligible=fullExamEligibleQuestions(questions);assert.equal(questions.length,134);assert.equal(eligible.length,110);const s=createSession("full-exam",questions,110,0,()=>"full-carpentry");assert.equal(s.questionIds.length,110);assert.equal(new Set(s.questionIds).size,110);assert.ok(s.questionIds.every(id=>eligible.some(q=>q.id===id)));const samples=questions.filter(q=>q.editorialStatus==="sample");assert.equal(samples.length,24);assert.ok(samples.every(q=>!s.questionIds.includes(q.id)&&!isFullExamEligible(q)))});
test("Carpentry high-risk numeric and table answer keys remain fixed",()=>{const answer=(id:string)=>{const q=carpentryQuestions.find(x=>x.id===id)!;return q.correctAnswers.map(key=>q.answers.find(a=>a.id===key)!.text)};assert.deepEqual(answer("carpentry-004"),["1-1/2 inches"]);assert.deepEqual(answer("carpentry-005"),["3 inches"]);assert.deepEqual(answer("carpentry-006"),["3 inches"]);assert.deepEqual(answer("carpentry-012"),["Three 10d face nails"]);assert.deepEqual(answer("carpentry-007"),["Nominal 2x2"]);assert.deepEqual(answer("carpentry-010"),["4 feet on center"]);assert.ok(carpentryQuestions.find(q=>q.id==="carpentry-027")!.answers[1].text.includes("10 feet"));assert.deepEqual(answer("carpentry-021"),["6 feet on center"]);assert.deepEqual(answer("carpentry-031"),["3 feet on center"]);assert.deepEqual(answer("carpentry-034"),["450 pounds"]);assert.deepEqual(answer("carpentry-024"),["2x4"]);assert.deepEqual(answer("carpentry-026"),["2x6"]);assert.deepEqual(answer("carpentry-028"),["2x8"]);assert.deepEqual(answer("carpentry-030"),["NA / engineered design required"])});
