import type{Difficulty,EditorialStatus,PrimaryCategory,Question,QuestionType,VerificationStatus}from"./types.ts";
export const PRIMARY_CATEGORIES:readonly PrimaryCategory[]=["Plans and Specifications","Energy Code","Building Planning / Life Safety","Sitework","Footings and Foundations","Carpentry","Roofing","Exterior Finishes","Foam Plastic Insulation","Interior Finishes","Associated Issues","Job Site Safety","Minnesota Contractor Law / Business"];
export const TRAINING_SUBCATEGORIES=["Plans","Foundations","Framing","Floors","Walls","Roof Framing","Stairs","Guards & Handrails","Egress","Required Exit Door","Emergency Escape and Rescue","Smoke Alarms","House / Garage Separation","Natural Light and Ventilation","Minimum Ceiling Heights","Replacement Windows","Windows & Doors","Safety Glazing","Decks","Roofing","Exterior","Insulation / Energy","Drywall","Sitework / Soils","Job Site Safety","Minnesota Contractor Law","Business / Licensing"] as const;
const DIFFICULTIES:readonly Difficulty[]=["easy","medium","exam"],TYPES:readonly QuestionType[]=["single","multiple"],STATUSES:readonly EditorialStatus[]=["sample","draft","reviewed"],VERIFICATIONS:readonly VerificationStatus[]=["unverified","source-checked"];
export interface ValidationIssue{questionId:string;field:string;message:string}
const strings=(value:unknown)=>Array.isArray(value)&&value.every(x=>typeof x==="string");
const preciseSection=(value:string|undefined)=>Boolean(value?.trim()&&!/pending|not established|tbd|todo/i.test(value));
export function validateQuestionBank(bank:readonly Question[]):ValidationIssue[]{const issues:ValidationIssue[]=[],seen=new Set<string>();for(const q of bank){const id=typeof q.id==="string"&&q.id.trim()?q.id:"(missing id)";const add=(field:string,message:string)=>issues.push({questionId:id,field,message});if(seen.has(id))add("id","Question ID must be unique");seen.add(id);if(!q.question?.trim())add("question","English question is required");if(!q.questionUk?.trim())add("questionUk","Ukrainian translation is required");if(!q.explanation?.trim())add("explanation","Explanation is required");if(!q.reference?.source?.trim())add("reference","Reference source is required");if(q.verificationStatus==="source-checked"&&!preciseSection(q.reference?.section))add("reference.section","Source-checked questions require a precise reference section");if(!PRIMARY_CATEGORIES.includes(q.primaryCategory))add("primaryCategory","Unknown primary category");if(!TRAINING_SUBCATEGORIES.includes(q.subcategory as typeof TRAINING_SUBCATEGORIES[number]))add("subcategory","Unknown training subcategory");if(!DIFFICULTIES.includes(q.difficulty))add("difficulty","Invalid difficulty");if(!TYPES.includes(q.type))add("type","Invalid question type");if(!STATUSES.includes(q.editorialStatus))add("editorialStatus","Invalid editorial status");if(!VERIFICATIONS.includes(q.verificationStatus))add("verificationStatus","Invalid verification status");if(!Array.isArray(q.answers)||![4,5].includes(q.answers.length))add("answers","Exactly 4 or 5 answers are required");const answerIds=new Set<string>();for(const a of q.answers??[]){if(!a.id?.trim())add("answers.id","Answer ID is required");if(answerIds.has(a.id))add("answers.id","Answer IDs must be unique within a question");answerIds.add(a.id);if(!a.text?.trim())add("answers.text","Answer text is required")}if(!Array.isArray(q.correctAnswers))add("correctAnswers","Correct answers must be an array");else{const unique=new Set(q.correctAnswers);if(unique.size!==q.correctAnswers.length)add("correctAnswers","Correct answer IDs must not repeat");if(q.correctAnswers.some(x=>!answerIds.has(x)))add("correctAnswers","Every correct answer ID must exist in answers");if(q.type==="single"&&q.correctAnswers.length!==1)add("correctAnswers","Single-choice questions require exactly one correct answer");if(q.type==="multiple"&&q.correctAnswers.length<2)add("correctAnswers","Multiple-select questions require at least two correct answers");if(q.requiredSelections!==undefined&&q.requiredSelections!==q.correctAnswers.length)add("requiredSelections","Required selections must match correct answer count")}if(!strings(q.languageTags)||q.languageTags.some(x=>!x.trim()))add("languageTags","Language tags must be non-empty strings");if(!strings(q.skills)||q.skills.some(x=>!x.trim()))add("skills","Skills must be non-empty strings")}return issues}
export function isFullExamEligible(q:Question):boolean{return q.editorialStatus==="reviewed"&&q.verificationStatus==="source-checked"&&q.answers.length===5&&validateQuestionBank([q]).length===0}
export function fullExamEligibleQuestions(bank:readonly Question[]):Question[]{return bank.filter(isFullExamEligible)}
