import type{Attempt,Profile,Session}from"./types.ts";
const K={profile:"mnqb:v1:profile",active:"mnqb:v1:active",attempts:"mnqb:v1:attempts",latest:"mnqb:v1:latest"};
function parse(key:string):unknown{if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem(key)??"null")}catch{return null}}
function write(key:string,value:unknown){if(typeof window!=="undefined")localStorage.setItem(key,JSON.stringify(value))}
const object=(x:unknown):x is Record<string,unknown>=>typeof x==="object"&&x!==null;
const profileValid=(x:unknown):x is Profile=>object(x)&&typeof x.name==="string"&&!!x.name.trim()&&typeof x.createdAt==="number";
const currentBankVersion=(x:unknown):unknown=>object(x)&&x.questionBankVersion===undefined?{...x,questionBankVersion:1}:x;
const sessionValid=(x:unknown):x is Session=>object(x)&&x.questionBankVersion===1&&typeof x.id==="string"&&["full-exam","quick-test","category-practice"].includes(String(x.mode))&&typeof x.startedAt==="number"&&Array.isArray(x.questionIds)&&x.questionIds.length>0&&x.questionIds.every(v=>typeof v==="string")&&new Set(x.questionIds).size===x.questionIds.length&&typeof x.currentIndex==="number"&&x.currentIndex>=0&&x.currentIndex<x.questionIds.length&&object(x.selectedAnswers)&&Array.isArray(x.flaggedQuestionIds)&&object(x.questionTimeSeconds)&&typeof x.activeQuestionEnteredAt==="number"&&Array.isArray(x.checkedQuestionIds);
const attemptValid=(x:unknown):x is Attempt=>object(x)&&x.questionBankVersion===1&&typeof x.id==="string"&&Array.isArray(x.questionIds)&&new Set(x.questionIds).size===x.questionIds.length&&object(x.selectedAnswers)&&object(x.correctness)&&object(x.questionTimeSeconds)&&Array.isArray(x.flaggedQuestionIds)&&typeof x.completedAt==="number"&&typeof x.percentage==="number"&&typeof x.correct==="number"&&typeof x.incorrect==="number"&&typeof x.unanswered==="number";
export function upsertAttempt(attempts:Attempt[],attempt:Attempt){return[attempt,...attempts.filter(a=>a.id!==attempt.id)]}
export const storage={profile:()=>{const x=parse(K.profile);return profileValid(x)?x:null},saveProfile:(p:Profile)=>write(K.profile,p),clearProfile:()=>{if(typeof window!=="undefined")localStorage.removeItem(K.profile)},active:()=>{const x=currentBankVersion(parse(K.active));return sessionValid(x)?x:null},saveActive:(s:Session)=>write(K.active,s),clearActive:()=>{if(typeof window!=="undefined")localStorage.removeItem(K.active)},attempts:()=>{const x=parse(K.attempts);return Array.isArray(x)?x.map(currentBankVersion).filter(attemptValid):[]},complete:(a:Attempt)=>{write(K.attempts,upsertAttempt(storage.attempts(),a));write(K.latest,a);if(typeof window!=="undefined")localStorage.removeItem(K.active)},latest:()=>{const x=currentBankVersion(parse(K.latest));return attemptValid(x)?x:null}};
