export type Difficulty="easy"|"medium"|"exam"; export type QuestionType="single"|"multiple";
export type EditorialStatus="sample"|"draft"|"reviewed"; export type VerificationStatus="unverified"|"source-checked";
export type PrimaryCategory="Plans and Specifications"|"Energy Code"|"Building Planning / Life Safety"|"Sitework"|"Footings and Foundations"|"Carpentry"|"Roofing"|"Exterior Finishes"|"Foam Plastic Insulation"|"Interior Finishes"|"Associated Issues"|"Job Site Safety"|"Minnesota Contractor Law / Business";
export interface QuestionReference{source:string;section?:string;subsection?:string;title?:string;note?:string}
export interface Question{ id:string;primaryCategory:PrimaryCategory;subcategory:string;difficulty:Difficulty;type:QuestionType;question:string;questionUk:string;answers:{id:string;text:string}[];correctAnswers:string[];requiredSelections?:number;explanation:string;reference?:QuestionReference;tags:string[];languageTags:string[];skills:string[];editorialStatus:EditorialStatus;verificationStatus:VerificationStatus }
export type SessionMode="full-exam"|"quick-test"|"category-practice";
export interface Session{id:string;questionBankVersion:number;mode:SessionMode;startedAt:number;completedAt?:number;timeLimitSeconds?:number;questionIds:string[];currentIndex:number;selectedAnswers:Record<string,string[]>;flaggedQuestionIds:string[];questionTimeSeconds:Record<string,number>;activeQuestionEnteredAt:number;checkedQuestionIds:string[]}
export interface Attempt{ id:string;questionBankVersion:number;mode:SessionMode;startedAt:number;completedAt:number;durationSeconds:number;questionIds:string[];selectedAnswers:Record<string,string[]>;correctness:Record<string,boolean>;questionTimeSeconds:Record<string,number>;flaggedQuestionIds:string[];correct:number;incorrect:number;unanswered:number;percentage:number;passed:boolean }
export interface Profile{name:string;createdAt:number}
